manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sayu-hub # 変更
      url-base: https://github.com/sayu-hub # 変更
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: sayu-hub # 変更
      revision: main
  self:
    path: config
